### ISSUE TITLE
Progress: D&I Updates for 2020-04-08

### ISSUE THREAD

**Issue by SMotaal** [badging/meta#18]
This issue tracks bi-weekly progress and updates for the [CHAOSS Diversity and Inclusion Working Group](https://github.com/chaoss/wg-diversity-inclusion).

---

**Agenda** `Mar25` thru `Mar29`

- [x] Review @bistaastha's Proposal #12
  > **Due** `Mar29`

- [x] Mention Milestones to our "Soft" launch #13
  > **MVP** applicants walking through process from start to finish
  >
  > per `Mar25` D&I meet

- [x] Begin articulating Terms and Conditions Requirements #15
  > **Draft** CHAOSS Conformance Requirements section
  >
  > per `Mar11` LF sync-up

**Agenda** `Mar30` thru `Apr05`

- [x] Review @thecraftman's Proposal #11
  > **Due** `Apr07`

- [x] Discuss GitLab parity #14
  > - [x] @Nebrethar create file to speculate on changes
  >
  > [Google Doc](https://docs.google.com/document/d/1r4j5VmgxA_WXiGkx7XYfdzHUIX46hs0ziqErE59CxNQ/edit?usp=sharing)
  >
  > per `Mar25`

---

**Related Threads**

- Agenda Card — https://github.com/badging/meta/projects/1#card-35152104
- Agenda Card — https://github.com/badging/meta/projects/1#card-35357620
