### ISSUE TITLE
Chore: Create a project coordination inbox for external correspondence!

### ISSUE THREAD

**Issue by SMotaal** [badging/meta#20]
This issue documents the creation of the chaoss.badging@gmail.com as the project coordination inbox for all external correspondence.

The following members have access to the account credentials:

- @SMotaal 
- @Nebrethar 

**TODOs**

- [ ] Subscribe chaoss.badging@gmail.com
- [ ] Unsubscribe chaoss-badging@googlegroups.com
- [ ] Retire chaoss-badging@googlegroups.com
- [ ] Keep the account credentials in the single-source doc shared by @germonprez with project coordinators

**Comment by SMotaal** [comment]
We're switching to chaoss.badging@gmail.com.

**Comment by SMotaal** [comment]
@germonprez 

We want to keep a shared document for project coordination-related accounts and credentials… etc.

Thoughts?
